spring:
  application:
    name: codeplanet
  jpa:
    properties:
      hibernate:
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: jdbc:mysql://localhost:3306/codeplanet

jwt:
  secret:
    key: ${JWT_KEY}