### 유저 회원 가입
POST http://localhost:8080/users
Content-Type: application/json

{
  "username":"{{username}}",
  "nickname":"{{nickname}}",
  "password":"{{password}}",
  "email":"{{email}}",
  "intro": "{{intro}}"
}

### 유저 회원 가입
POST http://localhost:8080/users
Content-Type: application/json

{
  "username":"asdfsafe4514",
  "nickname":"jakeopoc",
  "password":"nada5011!@@#AS",
  "email":"muzidea0808@gmail.com",
  "intro": "hahahahah"
}

### 로그인
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "username":"{{username}}",
  "password":"{{password}}"
}

> {%
  client.log(response.headers.valueOf("accessToken"));
  client.log(response.headers.valueOf("refreshToken"));
  client.global.set("accessToken", response.headers.valueOf("accessToken"));
  client.global.set("refreshToken", response.headers.valueOf("refreshToken"));
%}


### 이메일 인증 코드 전송
POST http://localhost:8080/email
Content-Type: application/json

{
  "email": "{{email}}"
}

### 인증 코드 확인
POST http://localhost:8080/email/verify
Content-Type: application/json

{
  "email": "{{email}}",
  "authCode": "iJofmKC1"
}